name: act-matrix-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip

  - flask=1.1.*
  - flask-sqlalchemy=2.4.*
  - psycopyg2=2.8.*

  # test dependencies
  - black=19.10b0
  - flake8
  - isort>=4.0.0,<5.0.0
  - pytest
